#ifndef SETTINGS_H
#define SETTINGS_H

#define BUFFER_SIZE 2048
#define FILTER_FREQ 400

typedef enum {
    PEAKDETECT_INITIAL,
    PEAKDETECT_POSITIVE,
    PEAKDETECT_NEGATIVE,
    PEAKDETECT_FINAL,
} PeakDetectState;

#endif // SETTINGS_H
